name: easy_avator_cropper
description: A simple and easy to use flutter plugin to crop image on iOS and Android.
version: 1.0.0
homepage: https://github.com/lvzhiyi/easy_avator_cropper.git

environment:
    sdk: '>=3.4.3 <4.0.0'
    flutter: '>=3.3.0'

dependencies:
    image: ^4.2.0
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    plugin:
      platforms:
        ios:
            pluginClass: SimpleImageCropPlugin
        android:
            package: com.lykhonis.simpleimagecrop
            pluginClass: SimpleImageCropPlugin
