name: easy_image_cropper
description: A simple image cropping widget that easily allows cropping avatars and other images.
version: 1.0.3
tags:
    - avatar
    - cropper
    - image_cropper
    - image_picker
    - avatar_cropper
homepage: https://github.com/lvzhiyi/easy_avator_cropper.git

environment:
    sdk: '>=3.4.0 <4.0.0'
    flutter: '>=3.3.0'

dependencies:
    image: ^4.2.0
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    plugin:
      platforms:
        ios:
            pluginClass: SimpleImageCropPlugin
        android:
            package: com.lykhonis.simpleimagecrop
            pluginClass: SimpleImageCropPlugin
